# Generated by Django 5.1.6 on 2025-02-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=255)),
                ('answer', models.TextField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
